name: Go CI
run-name: GitHub Actions for Go CI pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.0'
      
      - name: Run fmt
        run: |
          go fmt ./...

      - name: Run vet
        run: |
          go vet ./...

      - name: Run golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./...

      - name: Run build
        run: go build -o app .

      - name: Run app
        run: ./app
