name: Go CI
run-name: GitHub Actions for Go CI pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.0'
      
      - name: go fmt
        run: go fmt ./...

      - name: go vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2

      - name: Run build
        run: go build -o app .

      - name: Run app
        run: ./app
